### ISSUE TITLE
cURL error: [60] Peer certificate cannot be authenticated with known CA certificates

### ISSUE THREAD

**Issue by metalgigio** [Quixotix/PHP-PayPal-IPN#40]
It's a couple of days that it returns this error:

cURL error: [60] Peer certificate cannot be authenticated with known CA certificates

i noticed that everything goes fine through sandbox...
does anyone experienced this error?
thanks in advance

**Comment by petert82** [comment]
Yep, see #39

**Comment by metalgigio** [comment]
Thanks u so much!

**Comment by krishnaiitd** [comment]
@metalgigio Yes when I tried to connect my host system with virtual box (vagrant system), getting above error, I am able to access from web-bowers, but not able to connect while using Curl in php script.
